version: "3"

services:
  minio:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
      - "9001:9001"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_CONSOLE_ADDRESS=:9001
      - MINIO_BROWSER_REDIRECT_URL=localhost:9001/minio/
      - MINIO_SERVER_URL=s3.alzhanov.ru
      - VIRTUAL_HOST=s3.alzhanov.ru
      - VIRTUAL_PORT=9000
    command: server /data
    networks:
      - proxy

volumes:
  data:

networks:
  proxy:
    external: true

