version: "3"

services:
  minio:
    image: minio
    ports:
      - "9000:9000"
    volumes:
      - ./data:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data
