// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: api/v1/drinkollect.proto

package drinkollect

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Drinkollect_Register_FullMethodName            = "/drinkollect.v1.Drinkollect/Register"
	Drinkollect_Login_FullMethodName               = "/drinkollect.v1.Drinkollect/Login"
	Drinkollect_ChangePassword_FullMethodName      = "/drinkollect.v1.Drinkollect/ChangePassword"
	Drinkollect_DeleteAccount_FullMethodName       = "/drinkollect.v1.Drinkollect/DeleteAccount"
	Drinkollect_CreatePost_FullMethodName          = "/drinkollect.v1.Drinkollect/CreatePost"
	Drinkollect_ListPosts_FullMethodName           = "/drinkollect.v1.Drinkollect/ListPosts"
	Drinkollect_TogglePostLike_FullMethodName      = "/drinkollect.v1.Drinkollect/TogglePostLike"
	Drinkollect_ListUserPosts_FullMethodName       = "/drinkollect.v1.Drinkollect/ListUserPosts"
	Drinkollect_SendFriendRequest_FullMethodName   = "/drinkollect.v1.Drinkollect/SendFriendRequest"
	Drinkollect_AcceptFriendRequest_FullMethodName = "/drinkollect.v1.Drinkollect/AcceptFriendRequest"
	Drinkollect_RejectFriendRequest_FullMethodName = "/drinkollect.v1.Drinkollect/RejectFriendRequest"
	Drinkollect_ListFriendRequests_FullMethodName  = "/drinkollect.v1.Drinkollect/ListFriendRequests"
	Drinkollect_ListFriends_FullMethodName         = "/drinkollect.v1.Drinkollect/ListFriends"
	Drinkollect_RemoveFriend_FullMethodName        = "/drinkollect.v1.Drinkollect/RemoveFriend"
	Drinkollect_ListUsers_FullMethodName           = "/drinkollect.v1.Drinkollect/ListUsers"
	Drinkollect_ListFriendsPosts_FullMethodName    = "/drinkollect.v1.Drinkollect/ListFriendsPosts"
)

// DrinkollectClient is the client API for Drinkollect service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DrinkollectClient interface {
	// Register registers a new user and returns a token to be used for authorization.
	// InvalidArgument is returned if one of the request parameters is invalid.
	// AlreadyExists is returned if a user with such username already exists.
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Login logins an existing user and returns a token to be used for authorization.
	// InvalidArgument is returned if no such user exists or the password is invalid.
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// ChangePassword changes an authorized user's password.
	// InvalidArgument is returned if the specified password doesn't match the one in the DB.
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// DeleteAccount deletes the authorized user's account.
	DeleteAccount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// CreatePost creates a new post for an authorized user.
	// InvalidArgument is returned if the post title is empty. Other arguments aren't validated.
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListPosts lists all created posts.
	// This endpoint doesn't require authorization.
	ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error)
	// TogglePostLike toggles the "liked" label a specific post by the current user.
	// NotFound is returned if no such post exists. This should never occur, since the post ID is taken from the response of ListPosts/ListUserPosts.
	TogglePostLike(ctx context.Context, in *TogglePostLikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListUserPosts lists the post of a specific user and returns the total number of posts the user has.
	// This endpoint doesn't require authorization.
	ListUserPosts(ctx context.Context, in *ListUserPostsRequest, opts ...grpc.CallOption) (*ListUserPostsResponse, error)
	// SendFriendRequest sends a friend request to a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user is already a friend.
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// AcceptFriendRequest accepts a friend request from a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user hasn't sent a friend request.
	AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// RejectFriendRequest rejects a friend request from a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user hasn't sent a friend request.
	RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListFriendRequests lists all friend requests sent to the current user.
	ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error)
	// ListFriends lists all friends of the user.
	// This endpoint doesn't require authorization.
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	// RemoveFriend removes a friend from the user's friend list.
	// InvalidArgument is returned if the specified user doesn't exist or the user isn't a friend.
	RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ListUsers finds users by username wildcard.
	// This endpoint doesn't require authorization.
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	// ListFriendsPosts lists all posts of the current user's friends.
	ListFriendsPosts(ctx context.Context, in *ListFriendsPostsRequest, opts ...grpc.CallOption) (*ListFriendsPostsResponse, error)
}

type drinkollectClient struct {
	cc grpc.ClientConnInterface
}

func NewDrinkollectClient(cc grpc.ClientConnInterface) DrinkollectClient {
	return &drinkollectClient{cc}
}

func (c *drinkollectClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, Drinkollect_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, Drinkollect_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_ChangePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) DeleteAccount(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_DeleteAccount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_CreatePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListPosts(ctx context.Context, in *ListPostsRequest, opts ...grpc.CallOption) (*ListPostsResponse, error) {
	out := new(ListPostsResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) TogglePostLike(ctx context.Context, in *TogglePostLikeRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_TogglePostLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListUserPosts(ctx context.Context, in *ListUserPostsRequest, opts ...grpc.CallOption) (*ListUserPostsResponse, error) {
	out := new(ListUserPostsResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListUserPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_SendFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) AcceptFriendRequest(ctx context.Context, in *AcceptFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_AcceptFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) RejectFriendRequest(ctx context.Context, in *RejectFriendRequestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_RejectFriendRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListFriendRequests(ctx context.Context, in *ListFriendRequestsRequest, opts ...grpc.CallOption) (*ListFriendRequestsResponse, error) {
	out := new(ListFriendRequestsResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListFriendRequests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListFriends_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) RemoveFriend(ctx context.Context, in *RemoveFriendRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Drinkollect_RemoveFriend_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *drinkollectClient) ListFriendsPosts(ctx context.Context, in *ListFriendsPostsRequest, opts ...grpc.CallOption) (*ListFriendsPostsResponse, error) {
	out := new(ListFriendsPostsResponse)
	err := c.cc.Invoke(ctx, Drinkollect_ListFriendsPosts_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DrinkollectServer is the server API for Drinkollect service.
// All implementations must embed UnimplementedDrinkollectServer
// for forward compatibility
type DrinkollectServer interface {
	// Register registers a new user and returns a token to be used for authorization.
	// InvalidArgument is returned if one of the request parameters is invalid.
	// AlreadyExists is returned if a user with such username already exists.
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Login logins an existing user and returns a token to be used for authorization.
	// InvalidArgument is returned if no such user exists or the password is invalid.
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// ChangePassword changes an authorized user's password.
	// InvalidArgument is returned if the specified password doesn't match the one in the DB.
	ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error)
	// DeleteAccount deletes the authorized user's account.
	DeleteAccount(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	// CreatePost creates a new post for an authorized user.
	// InvalidArgument is returned if the post title is empty. Other arguments aren't validated.
	CreatePost(context.Context, *CreatePostRequest) (*emptypb.Empty, error)
	// ListPosts lists all created posts.
	// This endpoint doesn't require authorization.
	ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error)
	// TogglePostLike toggles the "liked" label a specific post by the current user.
	// NotFound is returned if no such post exists. This should never occur, since the post ID is taken from the response of ListPosts/ListUserPosts.
	TogglePostLike(context.Context, *TogglePostLikeRequest) (*emptypb.Empty, error)
	// ListUserPosts lists the post of a specific user and returns the total number of posts the user has.
	// This endpoint doesn't require authorization.
	ListUserPosts(context.Context, *ListUserPostsRequest) (*ListUserPostsResponse, error)
	// SendFriendRequest sends a friend request to a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user is already a friend.
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*emptypb.Empty, error)
	// AcceptFriendRequest accepts a friend request from a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user hasn't sent a friend request.
	AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*emptypb.Empty, error)
	// RejectFriendRequest rejects a friend request from a specific user.
	// InvalidArgument is returned if the specified user doesn't exist or the user hasn't sent a friend request.
	RejectFriendRequest(context.Context, *RejectFriendRequestRequest) (*emptypb.Empty, error)
	// ListFriendRequests lists all friend requests sent to the current user.
	ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error)
	// ListFriends lists all friends of the user.
	// This endpoint doesn't require authorization.
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	// RemoveFriend removes a friend from the user's friend list.
	// InvalidArgument is returned if the specified user doesn't exist or the user isn't a friend.
	RemoveFriend(context.Context, *RemoveFriendRequest) (*emptypb.Empty, error)
	// ListUsers finds users by username wildcard.
	// This endpoint doesn't require authorization.
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	// ListFriendsPosts lists all posts of the current user's friends.
	ListFriendsPosts(context.Context, *ListFriendsPostsRequest) (*ListFriendsPostsResponse, error)
	mustEmbedUnimplementedDrinkollectServer()
}

// UnimplementedDrinkollectServer must be embedded to have forward compatible implementations.
type UnimplementedDrinkollectServer struct {
}

func (UnimplementedDrinkollectServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedDrinkollectServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedDrinkollectServer) ChangePassword(context.Context, *ChangePasswordRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedDrinkollectServer) DeleteAccount(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (UnimplementedDrinkollectServer) CreatePost(context.Context, *CreatePostRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedDrinkollectServer) ListPosts(context.Context, *ListPostsRequest) (*ListPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}
func (UnimplementedDrinkollectServer) TogglePostLike(context.Context, *TogglePostLikeRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TogglePostLike not implemented")
}
func (UnimplementedDrinkollectServer) ListUserPosts(context.Context, *ListUserPostsRequest) (*ListUserPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUserPosts not implemented")
}
func (UnimplementedDrinkollectServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedDrinkollectServer) AcceptFriendRequest(context.Context, *AcceptFriendRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptFriendRequest not implemented")
}
func (UnimplementedDrinkollectServer) RejectFriendRequest(context.Context, *RejectFriendRequestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectFriendRequest not implemented")
}
func (UnimplementedDrinkollectServer) ListFriendRequests(context.Context, *ListFriendRequestsRequest) (*ListFriendRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFriendRequests not implemented")
}
func (UnimplementedDrinkollectServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedDrinkollectServer) RemoveFriend(context.Context, *RemoveFriendRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFriend not implemented")
}
func (UnimplementedDrinkollectServer) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedDrinkollectServer) ListFriendsPosts(context.Context, *ListFriendsPostsRequest) (*ListFriendsPostsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFriendsPosts not implemented")
}
func (UnimplementedDrinkollectServer) mustEmbedUnimplementedDrinkollectServer() {}

// UnsafeDrinkollectServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DrinkollectServer will
// result in compilation errors.
type UnsafeDrinkollectServer interface {
	mustEmbedUnimplementedDrinkollectServer()
}

func RegisterDrinkollectServer(s grpc.ServiceRegistrar, srv DrinkollectServer) {
	s.RegisterService(&Drinkollect_ServiceDesc, srv)
}

func _Drinkollect_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_DeleteAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).DeleteAccount(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListPosts(ctx, req.(*ListPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_TogglePostLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TogglePostLikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).TogglePostLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_TogglePostLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).TogglePostLike(ctx, req.(*TogglePostLikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListUserPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListUserPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListUserPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListUserPosts(ctx, req.(*ListUserPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_AcceptFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).AcceptFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_AcceptFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).AcceptFriendRequest(ctx, req.(*AcceptFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_RejectFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).RejectFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_RejectFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).RejectFriendRequest(ctx, req.(*RejectFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListFriendRequests(ctx, req.(*ListFriendRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_RemoveFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).RemoveFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_RemoveFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).RemoveFriend(ctx, req.(*RemoveFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Drinkollect_ListFriendsPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DrinkollectServer).ListFriendsPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Drinkollect_ListFriendsPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DrinkollectServer).ListFriendsPosts(ctx, req.(*ListFriendsPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Drinkollect_ServiceDesc is the grpc.ServiceDesc for Drinkollect service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Drinkollect_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "drinkollect.v1.Drinkollect",
	HandlerType: (*DrinkollectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Drinkollect_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Drinkollect_Login_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _Drinkollect_ChangePassword_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _Drinkollect_DeleteAccount_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Drinkollect_CreatePost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _Drinkollect_ListPosts_Handler,
		},
		{
			MethodName: "TogglePostLike",
			Handler:    _Drinkollect_TogglePostLike_Handler,
		},
		{
			MethodName: "ListUserPosts",
			Handler:    _Drinkollect_ListUserPosts_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _Drinkollect_SendFriendRequest_Handler,
		},
		{
			MethodName: "AcceptFriendRequest",
			Handler:    _Drinkollect_AcceptFriendRequest_Handler,
		},
		{
			MethodName: "RejectFriendRequest",
			Handler:    _Drinkollect_RejectFriendRequest_Handler,
		},
		{
			MethodName: "ListFriendRequests",
			Handler:    _Drinkollect_ListFriendRequests_Handler,
		},
		{
			MethodName: "ListFriends",
			Handler:    _Drinkollect_ListFriends_Handler,
		},
		{
			MethodName: "RemoveFriend",
			Handler:    _Drinkollect_RemoveFriend_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _Drinkollect_ListUsers_Handler,
		},
		{
			MethodName: "ListFriendsPosts",
			Handler:    _Drinkollect_ListFriendsPosts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/drinkollect.proto",
}
